import Head from "next/head";
import styles from "./../styles/Home.module.css"
import Header from "./../components/Header"
import SubHeader from "./../components/SubHeader"
import Input from "./../components/Input"

import { useState } from "react";
import { useQRCode } from 'next-qrcode';
import Menu from "@/components/Menu";


export default function Home() {
  const [text1, setText1] = useState('aa')

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setText1(() => e.target.value)
  }

  const [text2, setText2] = useState('aaa')

  const handleChange2 = (e: React.ChangeEvent<HTMLInputElement>) => {
    setText2(() => e.target.value)
  }

  const { Canvas } = useQRCode();
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className={styles.twice}>
        <Menu />
        <div className={styles.second}>
        <Input text={text1} handleChange={handleChange} />
        <Input text={text2} handleChange={handleChange2} />
        <Input text={text2} handleChange={handleChange2} />
        <Input text={text2} handleChange={handleChange2} />
        {(text1!="" && text2 != "") && (
          <Canvas
      text={text1+text2}
      options={{
        errorCorrectionLevel: 'M',
        margin: 3,
        scale: 4,
        width: 200,
        color: {
          dark: '#010599FF',
          light: '#FFBF60FF',
        },
      }}
    />
        )

        }
        
        </div>
        
        </div>
        
        
      </main>
    </>
  );
}
