import Head from "next/head";
import styles from "./../styles/Home.module.css";
import Header from "./../components/Header";
import React, { useState, useEffect } from 'react';

export default function Storage() {
    const [todos, setTodos] = useState([]);
    const [inputValue, setInputValue] = useState('');
  
    // LocalStorageからToDoリストを取得
    useEffect(() => {
      const storedTodos = JSON.parse(localStorage.getItem('todos'));
      if (storedTodos) {
        setTodos(storedTodos);
      }
    }, []);
  
    // ToDoリストの変更時にLocalStorageに保存
    useEffect(() => {
      localStorage.setItem('todos', JSON.stringify(todos));
    }, [todos]);
  
    const handleInputChange = (event) => {
      setInputValue(event.target.value);
    };
  
    const handleFormSubmit = (event) => {
      event.preventDefault();
      if (inputValue.trim() !== '') {
        setTodos([...todos, inputValue]);
        setInputValue('');
      }
    };
  
    const handleTodoDelete = (index) => {
      const newTodos = [...todos];
      newTodos.splice(index, 1);
      setTodos(newTodos);
    };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.progressbar}></div>
        <Header />
        <div>
      <h1>ToDo App</h1>
      <form onSubmit={handleFormSubmit}>
        <input
          type="text"
          value={inputValue}
          onChange={handleInputChange}
          placeholder="Add new todo..."
        />
        <button type="submit">Add</button>
      </form>
      <ul>
        {todos.map((todo, index) => (
          <li key={index}>
            {todo}
            <button onClick={() => handleTodoDelete(index)}>Delete</button>
          </li>
        ))}
      </ul>
    </div>
      </main>
    </>
  );
}
